theme: jekyll-theme-cayman
title: [Computational Systems Medicine]
description: [University of Vic - Central University of Catalonia
new line]
github:
  is_project_page: false
color:
  header: "#000"
  gradient_left: "#22c1c3"
  gradient_right: "#fdbb2d"
