theme: jekyll-theme-cayman

title: [Computational systems medicine course]

description: [
4 - 8 July 2022<br/> <br/>
Both online and onsite at BAU Barcelona<br/>
University of Vic - Central University of Catalonia<br/> <br/>
Registration is still open!
]

github:
  is_project_page: false

colors:
    gradient_left: "#155799"
    gradient_right: "#159957"
    header: "#fff"
    android_theme: "#000" # this default to gradient_color
    link: "#1e6bb8" # this default to gradient_color
    section_title: "#155799" # this default to gradient_color
