title: [Computational systems medicine course]

description: [
4 - 8 July 2022<br/> <br/>
Both online and onsite at BAU Barcelona<br/>
University of Vic - Central University of Catalonia
]

github:
  is_project_page: false

theme: jekyll-theme-cayman
