remote_theme: tuur29/pages-themes-cayman
title: [Computational systems medicine course]
description: [
4 - 8 July 2022<br/> <br/>
Both online and onsite at <a href="https://tinyurl.com/y8prsend">BAU Barcelona</a><br/>
University of Vic - Central University of Catalonia<br/> <br/>
<a href="https://tinyurl.com/5sznepef">Registration is still open!</a>]
github:
  is_project_page: false
