theme: jekyll-theme-cayman
title: [Computational systems medicine course]
description: [4 - 8 July 2022<br/>Both online and onsite at [BAU Barcelona](https://tinyurl.com/y8prsend)<br/>[University of Vic - Central University of Catalonia](https://www.uvic.cat/en)]
github:
  is_project_page: false
color:
  header: "#000"
  gradient_left: "#22c1c3"
  gradient_right: "#fdbb2d"
