#theme: jekyll-theme-cayman
#theme: jekyll-theme-minimal

plugins:
- jekyll-feed
- jekyll-remote-theme
remote_theme: tuur29/pages-themes-cayman

title: [Computational systems medicine course]

description: [
4 - 8 July 2022<br/> <br/>
Both online and onsite at BAU Barcelona<br/>
University of Vic - Central University of Catalonia<br/> <br/>
Registration is still open!
]

github:
  is_project_page: false
